# Generated by Django 5.0 on 2024-04-30 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0018_rename_message_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
