# Generated by Django 5.0 on 2024-04-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0015_apikey_alter_lphistory_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.CharField(max_length=200)),
                ('cooldown', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=200)),
            ],
        ),
    ]
