# Generated by Django 5.0 on 2024-04-30 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol_website', '0017_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='feedback',
        ),
    ]
